---
title: "분석 결과 (표)"
author: "안우진"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 14
    fig_height: 10
    fig.align : 'center'
    toc: yes
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = "")
```

<style type="text/css">
.main-container {
max-width: 1200px;
margin-left: auto;
margin-right: auto;
}
</style>

# 패키지 로드 및 옵션 설정

```{r}
rm(list = ls())

library(dplyr)
library(ggplot2)
library(ggpubr)
library(glue)
library(kableExtra)
library(latex2exp)
library(lawstat)
library(purrr)
library(readr)
library(wPerm)

options(scipen = 999) # turn-off scientific notation like 1e+48
options(tibble.width = Inf)
theme_set(theme_bw())
source("./functions_table.R")
```

<hr>

<div style="margin-bottom:60px;"></div>

```{r}
data <- read_csv("./data/실험수치.csv")
variables <- c("알레르기", "시간", "지표", "정규성 p-value", "정규성 결과", "검정 방법", "검정 p-value", "검정 결과", "순열 검정 p-value", "순열 검정 결과", "요약")
df <- variables %>% map_dfc(setNames, object = list(character()))
df2 <- variables %>% map_dfc(setNames, object = list(character()))
df3 <- variables %>% map_dfc(setNames, object = list(character()))

# 알레르기 있는 샛별이와 송이를 포함한 결과 (n = 20)

for (time in c("30초", "1분", "2분", "4분")) {
  df <- bind_rows(df, get_paired_table(data, time = time))
}

for (times in list(c("30초", "1분", "2분", "4분"), c("30초", "1분", "2분"))){
  for (variable in c("TEWL", "SH", "Tem")) {
    df2 <- bind_rows(df2, get_multiple_table(data, variable = variable, times = times))
  }
}

for (times in list(c("30초", "1분", "2분", "4분"), c("30초", "1분", "2분"))){
  for (variable in c("TEWL", "SH", "Tem")) {
    df3 <- bind_rows(df3, get_after_table(data, variable = variable, times = times))
  }
}

# 알레르기 있는 샛별이와 송이를 포함하지 않은 결과 (n = 18)

data <- data %>% filter(Name %!in% c("샛별이", "송이"))

for (time in c("30초", "1분", "2분", "4분")) {
  df <- bind_rows(df, get_paired_table(data, time = time))
}

for (times in list(c("30초", "1분", "2분", "4분"), c("30초", "1분", "2분"))){
  for (variable in c("TEWL", "SH", "Tem")) {
    df2 <- bind_rows(df2, get_multiple_table(data, variable = variable, times = times))
  }
}

for (times in list(c("30초", "1분", "2분", "4분"), c("30초", "1분", "2분"))){
  for (variable in c("TEWL", "SH", "Tem")) {
    df3 <- bind_rows(df3, get_after_table(data, variable = variable, times = times))
  }
}
```

<hr>

<div style="margin-bottom:60px;"></div>

# 분석 1

```{r}
df %>% arrange(지표) %>% kbl() %>% kable_paper() %>% scroll_box(width = "1500px", height = "800px")
```

# 분석 2

```{r}
df2 %>% arrange(지표) %>% kbl() %>% kable_paper() %>% scroll_box(width = "1500px", height = "700px")
```

# 분석 3

```{r}
df3 %>% arrange(지표) %>% kbl() %>% kable_paper() %>% scroll_box(width = "1500px", height = "700px")
```

# 시간에 따른 피부 장벽 기능 지표 변화

```{r}
data <- read_csv("./data/실험수치.csv")
data <- data %>% rename(`Measurement Time` = Time)
level <- c("30초 Before", "30초 After", "1분 Before", "1분 After", "2분 Before", "2분 After", "4분 Before", "4분 After")
new_label <- c("30s Before", "30s After", "1m Before", "1m After", "2m Before", "2m After", "4m Before", "4m After")
data <- data %>% mutate(`Measurement Time` = factor(`Measurement Time`, levels = level, labels = new_label))
data <- data %>% mutate(Time = factor(rep(c("30s", "1m", "2m", "4m"), each = 2, times = 20), levels = c("30s", "1m", "2m", "4m")))
```

```{r}
tewl_plot <- data %>% 
  select(Time, `Measurement Time`, TEWL_Mean) %>% 
  group_by(Time, `Measurement Time`) %>% 
  summarise(TEWL = round(mean(TEWL_Mean), 2), TEWL_se = sd(TEWL_Mean) / sqrt(nrow(data)/8)) %>% 
  ggplot(aes(x = Time, y = TEWL, fill = `Measurement Time`)) +
  geom_bar(stat = "identity", width = 0.5, position = position_dodge()) +
  geom_errorbar(aes(ymin = TEWL - TEWL_se, ymax = TEWL + TEWL_se), width = 0.2, color = "black", position = position_dodge(0.5)) +
  scale_fill_manual("legend", values = c("30s Before" = "gray 45", "30s After" = "gray 25", "1m Before" = "gray 45", "1m After" = "gray 25", "2m Before" = "gray 45", "2m After" = "gray 25", "4m Before" = "gray 45", "4m After" = "gray 25")) +
  labs(x = "") +
  ylim(c(0, 20)) + 
  theme(legend.position = "none", axis.line=element_blank())

sh_plot <- data %>% 
  select(Time, `Measurement Time`, SH_Mean) %>% 
  group_by(Time, `Measurement Time`) %>% 
  summarise(SH = round(mean(SH_Mean), 2), SH_se = sd(SH_Mean) / sqrt(nrow(data)/8)) %>% 
  ggplot(aes(x = Time, y = SH, fill = `Measurement Time`)) +
  geom_bar(stat = "identity", width = 0.5, position = position_dodge()) +
  geom_errorbar(aes(ymin = SH - SH_se, ymax = SH + SH_se), width = 0.2, color = "black", position = position_dodge(0.5)) +
  scale_fill_manual("legend", values = c("30s Before" = "gray 45", "30s After" = "gray 25", "1m Before" = "gray 45", "1m After" = "gray 25", "2m Before" = "gray 45", "2m After" = "gray 25", "4m Before" = "gray 45", "4m After" = "gray 25")) +
  labs(x = "") +
  ylim(c(0, 20)) + 
  theme(legend.position = "none")

tem_plot <- data %>% 
  select(Time, `Measurement Time`, Tem_Mean) %>% 
  group_by(Time, `Measurement Time`) %>% 
  summarise(Tem = round(mean(Tem_Mean), 2), Tem_se = sd(Tem_Mean) / sqrt(nrow(data)/8)) %>% 
  ggplot(aes(x = Time, y = Tem, fill = `Measurement Time`)) +
  geom_bar(stat = "identity", width = 0.5, position = position_dodge()) +
  geom_errorbar(aes(ymin = Tem - Tem_se, ymax = Tem + Tem_se), width = 0.2, color = "black", position = position_dodge(0.5)) +
  scale_fill_manual("legend", values = c("30s Before" = "gray 45", "30s After" = "gray 25", "1m Before" = "gray 45", "1m After" = "gray 25", "2m Before" = "gray 45", "2m After" = "gray 25", "4m Before" = "gray 45", "4m After" = "gray 25")) +
  ylim(c(0, 40)) + 
  theme(legend.position = "none")

ggarrange(tewl_plot, sh_plot, tem_plot, nrow = 3)
```

# 상자그림으로 평균값 비교

## TEWL

```{r}
data %>%
  ggplot(aes(x = `Measurement Time`, y = TEWL_Mean)) +
  geom_boxplot(linetype = "dashed") +
  stat_boxplot(aes(ymin = ..lower.., ymax = ..upper..)) +
  stat_boxplot(aes(ymin = ..ymax..), geom = "errorbar", width = 0.3) +
  stat_boxplot(aes(ymax = ..ymin..), geom = "errorbar", width = 0.3) +
  geom_point(aes(x = `Measurement Time`, y = TEWL_Mean), shape = "X", data = data %>% group_by(`Measurement Time`) %>% summarise(TEWL_Mean = mean(TEWL_Mean))) +
  labs(x ="Time", y = TeX("TEWL ($g/m^2/h$)")) +
  scale_x_discrete(limits = c("30s Before", "30s After", "", "1m Before", "1m After", "", "2m Before", "2m After", "", "4m Before", "4m After")) +
  ylim(c(0, 50))
```

## SH

```{r}
data %>%
  ggplot(aes(x = `Measurement Time`, y = SH_Mean)) +
  geom_boxplot(linetype = "dashed") +
  stat_boxplot(aes(ymin = ..lower.., ymax = ..upper..)) +
  stat_boxplot(aes(ymin = ..ymax..), geom = "errorbar", width = 0.3) +
  stat_boxplot(aes(ymax = ..ymin..), geom = "errorbar", width = 0.3) +
  geom_point(aes(x = `Measurement Time`, y = SH_Mean), shape = "X", data = data %>% group_by(`Measurement Time`) %>% summarise(SH_Mean = mean(SH_Mean))) +
  geom_bracket(xmin = "2m Before", xmax = "2m After", y.position = 50, label = "p < 0.05", label.size = 2.5) +
  labs(x ="Time", y = "Skin hydration (A.U.)") +
  scale_x_discrete(limits = c("30s Before", "30s After", "", "1m Before", "1m After", "", "2m Before", "2m After", "", "4m Before", "4m After")) +
  ylim(c(0, 60))
```

## Tem

```{r}
data %>%
  ggplot(aes(x = `Measurement Time`, y = Tem_Mean)) +
  geom_boxplot(linetype = "dashed") +
  stat_boxplot(aes(ymin = ..lower.., ymax = ..upper..)) +
  stat_boxplot(aes(ymin = ..ymax..), geom = "errorbar", width = 0.3) +
  stat_boxplot(aes(ymax = ..ymin..), geom = "errorbar", width = 0.3) +
  geom_point(aes(x = `Measurement Time`, y = Tem_Mean), shape = "X", data = data %>% group_by(`Measurement Time`) %>% summarise(Tem_Mean = mean(Tem_Mean))) +
  geom_bracket(xmin = "4m Before", xmax = "4m After", y.position = 39, label = "p < 0.05", label.size = 2.5) +
  labs(x ="Time", y = TeX("Temperature ($\\degree C$)")) +
  scale_x_discrete(limits = c("30s Before", "30s After", "", "1m Before", "1m After", "", "2m Before", "2m After", "", "4m Before", "4m After")) +
  ylim(c(35, 39))
```

# 각 시간별 세 지표 차이에 대한 95% 단측 신뢰구간

```{r}
data <- read_csv("./data/실험수치.csv")
df4 <- tibble(
  Time = character(),
  Variable = character(),
  Mean = numeric(),
  ymin = numeric(),
  ymax = numeric()
)

for (time in c("30초", "1분", "2분", "4분")) {
  df4 <- bind_rows(df4, get_paired_conf_int(data, time = time))  
}

df4 <- df4 %>% 
  mutate(
    Time = factor(Time, levels = c("30초", "1분", "2분", "4분"), labels = c("30s", "1m", "2m", "4m")),
    Variable = factor(Variable, levels = c("TEWL", "SH", "Tem"))
  )
```

```{r}
df4 %>% ggplot(aes(x = Time, y = Mean, fill = Variable)) + 
  geom_bar(stat = "identity", width = 0.5, position = position_dodge()) +
  geom_errorbar(aes(ymin = Mean, ymax = Mean), width = 0.2, color = "black", position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0.2, color = "black", position = position_dodge(0.5)) +
  scale_fill_manual("legend", values = c("TEWL" = "gray 65", "SH" = "gray 35", "Tem" = "gray 5")) +
  guides(fill = guide_legend("Skin barrier function\nparameters"))
```


# 실험 직후 데이터

```{r}
after_data <- read_csv("./data/실험_직후_데이터.csv")
```

## 각 지표의 빈도표

```{r}
after_data %>% select(-이름) %>% lapply(table)
```

## 합계 막대 그래프

```{r}
after_data %>% 
  count(합계) %>% 
  mutate(합계 = factor(합계, levels = 0:24)) %>% 
  ggplot(aes(x = 합계, y = n)) + 
  geom_bar(stat = "identity", width = 0.5) + 
  labs(x = "Sum", y = "Frequency")
```